server:
  port: 8083

spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./MSA-study/customer
    username: sa
    password: 1234
  zipkin:
    enabled: true
    service.name: customer
    sender.type: web
    base-url: http://localhost:9411/zipkin/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  #  file: C:\repositories\MSA-study\logs\catalogs.log
  file: ./logs/customers.log