server:
  port: 8083

spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./MSA-study/customer
    username: sa
    password: 1234

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka