server:
  port: 8081

spring:
  application:
    name: catalog

#Ribbon 의 listOfServers 목록은 Eureka 적용으로 불필요하여 주석처리

#customer:
#  ribbon:
#    listOfServers: localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka