server:
  port: 8081

spring:
  application:
    name: catalog
  zipkin:
    enabled: true
    service.name: catalog
    sender.type: web
    base-url: http://localhost:9411/zipkin/

#Ribbon 의 listOfServers 목록은 Eureka 적용으로 불필요하여 주석처리

#customer:
#  ribbon:
#    listOfServers: localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
#  file: C:\repositories\MSA-study\logs\catalogs.log
  file: ./logs/catalogs.log

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
#        include: "*"
        include: ['prometheus', 'health', 'info', 'metric']
  metrics:
    export:
      prometheus:
        enabled: true